package com.socialtime.model;
// Generated Mar 16, 2017 11:49:00 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name = "event", catalog = "socialtime"
)
public class Event implements java.io.Serializable {

    private int eventId;
    private Day day;
    private Hours hoursByStartTime;
    private Hours hoursByEndTime;
    private Users users;
    private String eventName;
    private String eventLocation;
    private int minAttendees;
    private int minTresholders;
    private Set<Eventvotes> eventvoteses = new HashSet<Eventvotes>(0);
    private Set<Eventinvitations> eventinvitationses = new HashSet<Eventinvitations>(0);

    public Event() {
    }

    public Event(int eventId, Day day, Hours hoursByStartTime, Hours hoursByEndTime, Users users, String eventName, String eventLocation, int minAttendees, int minTresholders) {
        this.eventId = eventId;
        this.day = day;
        this.hoursByStartTime = hoursByStartTime;
        this.hoursByEndTime = hoursByEndTime;
        this.users = users;
        this.eventName = eventName;
        this.eventLocation = eventLocation;
        this.minAttendees = minAttendees;
        this.minTresholders = minTresholders;
    }

    public Event(int eventId, Day day, Hours hoursByStartTime, Hours hoursByEndTime, Users users, String eventName, String eventLocation, int minAttendees, int minTresholders, Set<Eventvotes> eventvoteses, Set<Eventinvitations> eventinvitationses) {
        this.eventId = eventId;
        this.day = day;
        this.hoursByStartTime = hoursByStartTime;
        this.hoursByEndTime = hoursByEndTime;
        this.users = users;
        this.eventName = eventName;
        this.eventLocation = eventLocation;
        this.minAttendees = minAttendees;
        this.minTresholders = minTresholders;
        this.eventvoteses = eventvoteses;
        this.eventinvitationses = eventinvitationses;
    }

    @Id

    @Column(name = "eventId", unique = true, nullable = false)
    public int getEventId() {
        return this.eventId;
    }

    public void setEventId(int eventId) {
        this.eventId = eventId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "day", nullable = false)
    public Day getDay() {
        return this.day;
    }

    public void setDay(Day day) {
        this.day = day;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "startTime", nullable = false)
    public Hours getHoursByStartTime() {
        return this.hoursByStartTime;
    }

    public void setHoursByStartTime(Hours hoursByStartTime) {
        this.hoursByStartTime = hoursByStartTime;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "endTime", nullable = false)
    public Hours getHoursByEndTime() {
        return this.hoursByEndTime;
    }

    public void setHoursByEndTime(Hours hoursByEndTime) {
        this.hoursByEndTime = hoursByEndTime;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "hostEmail", nullable = false)
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "eventName", nullable = false, length = 200)
    public String getEventName() {
        return this.eventName;
    }

    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    @Column(name = "eventLocation", nullable = false, length = 250)
    public String getEventLocation() {
        return this.eventLocation;
    }

    public void setEventLocation(String eventLocation) {
        this.eventLocation = eventLocation;
    }

    @Column(name = "minAttendees", nullable = false)
    public int getMinAttendees() {
        return this.minAttendees;
    }

    public void setMinAttendees(int minAttendees) {
        this.minAttendees = minAttendees;
    }

    @Column(name = "minTresholders", nullable = false)
    public int getMinTresholders() {
        return this.minTresholders;
    }

    public void setMinTresholders(int minTresholders) {
        this.minTresholders = minTresholders;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
    public Set<Eventvotes> getEventvoteses() {
        return this.eventvoteses;
    }

    public void setEventvoteses(Set<Eventvotes> eventvoteses) {
        this.eventvoteses = eventvoteses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "event")
    public Set<Eventinvitations> getEventinvitationses() {
        return this.eventinvitationses;
    }

    public void setEventinvitationses(Set<Eventinvitations> eventinvitationses) {
        this.eventinvitationses = eventinvitationses;
    }

}
