package com.socialtime.model;
// Generated Mar 16, 2017 11:49:00 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Eventvotes generated by hbm2java
 */
@Entity
@Table(name = "eventvotes", catalog = "socialtime"
)
public class Eventvotes implements java.io.Serializable {

    private int poolId;
    private Event event;
    private Hours hoursByStartTimeId;
    private Hours hoursByEndTimeId;
    private int countVotes;

    public Eventvotes() {
    }

    public Eventvotes(int poolId, Event event, Hours hoursByStartTimeId, Hours hoursByEndTimeId, int countVotes) {
        this.poolId = poolId;
        this.event = event;
        this.hoursByStartTimeId = hoursByStartTimeId;
        this.hoursByEndTimeId = hoursByEndTimeId;
        this.countVotes = countVotes;
    }

    @Id

    @Column(name = "poolId", unique = true, nullable = false)
    public int getPoolId() {
        return this.poolId;
    }

    public void setPoolId(int poolId) {
        this.poolId = poolId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "eventId", nullable = false)
    public Event getEvent() {
        return this.event;
    }

    public void setEvent(Event event) {
        this.event = event;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "startTimeId", nullable = false)
    public Hours getHoursByStartTimeId() {
        return this.hoursByStartTimeId;
    }

    public void setHoursByStartTimeId(Hours hoursByStartTimeId) {
        this.hoursByStartTimeId = hoursByStartTimeId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "endTimeId", nullable = false)
    public Hours getHoursByEndTimeId() {
        return this.hoursByEndTimeId;
    }

    public void setHoursByEndTimeId(Hours hoursByEndTimeId) {
        this.hoursByEndTimeId = hoursByEndTimeId;
    }

    @Column(name = "countVotes", nullable = false)
    public int getCountVotes() {
        return this.countVotes;
    }

    public void setCountVotes(int countVotes) {
        this.countVotes = countVotes;
    }

}
