package com.socialtime.model;
// Generated Mar 16, 2017 11:49:00 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "socialtime"
)
public class Users implements java.io.Serializable {

    private String email;
    private String name;
    private String password;
    private String location;
    private Set<Userunavailability> userunavailabilities = new HashSet<Userunavailability>(0);
    private Set<Eventinvitations> eventinvitationses = new HashSet<Eventinvitations>(0);
    private Set<Useravailability> useravailabilities = new HashSet<Useravailability>(0);
    private Set<Event> events = new HashSet<Event>(0);

    public Users() {
    }

    public Users(String email, String name, String password, String location) {
        this.email = email;
        this.name = name;
        this.password = password;
        this.location = location;
    }

    public Users(String email, String name, String password, String location, Set<Userunavailability> userunavailabilities, Set<Eventinvitations> eventinvitationses, Set<Useravailability> useravailabilities, Set<Event> events) {
        this.email = email;
        this.name = name;
        this.password = password;
        this.location = location;
        this.userunavailabilities = userunavailabilities;
        this.eventinvitationses = eventinvitationses;
        this.useravailabilities = useravailabilities;
        this.events = events;
    }

    @Id

    @Column(name = "email", unique = true, nullable = false, length = 100)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "password", nullable = false, length = 200)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "location", nullable = false, length = 250)
    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "users")
    public Set<Userunavailability> getUserunavailabilities() {
        return this.userunavailabilities;
    }

    public void setUserunavailabilities(Set<Userunavailability> userunavailabilities) {
        this.userunavailabilities = userunavailabilities;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "users")
    public Set<Eventinvitations> getEventinvitationses() {
        return this.eventinvitationses;
    }

    public void setEventinvitationses(Set<Eventinvitations> eventinvitationses) {
        this.eventinvitationses = eventinvitationses;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "users")
    public Set<Useravailability> getUseravailabilities() {
        return this.useravailabilities;
    }

    public void setUseravailabilities(Set<Useravailability> useravailabilities) {
        this.useravailabilities = useravailabilities;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "users")
    public Set<Event> getEvents() {
        return this.events;
    }

    public void setEvents(Set<Event> events) {
        this.events = events;
    }

}
